server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/utilisateurs/**
        - id: user-composite-service
          uri: lb://user-service
          predicates:
            - Path=/api/utilisateurs/composite/**
        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/api/roles/**
        - id: permission-service
          uri: lb://permission-service
          predicates:
            - Path=/api/permissions/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

# Configuration Swagger/OpenAPI pour Gateway
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: http://localhost:8083/api-docs
      - name: Role Service
        url: http://localhost:8082/api-docs
      - name: Permission Service
        url: http://localhost:8081/api-docs
