server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/utilisateurs/**
        - id: user-composite-service
          uri: lb://user-service
          predicates:
            - Path=/api/utilisateurs/composite/**
        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/api/roles/**
        - id: permission-service
          uri: lb://permission-service
          predicates:
            - Path=/api/permissions/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
