server:
  port: 8761


spring:
  application:
    name: discovery-server
    cloud:
      config:
        enabled: false



eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
